package com.reForm.backend.ai.tool.port;

import tools.jackson.databind.JsonNode;

import java.util.Map;

/**
 * STRATEGY INTERFACE: MODE 2 TOOL HANDLER
 *
 * WHY A SEPARATE INTERFACE FROM IToolCallHandler:
 * Mode 2 is stateless HTTP, not a WebSocket session — there is no WebSocketSession to pass a
 * handler. Rather than generalizing IToolCallHandler's signature (which would force every Mode 3/4
 * handler and ToolCallRegistry call site to change), Mode 2 gets its own parallel Strategy Pattern.
 * Tools reused from Mode 3/4 (e.g. publishForm) share their real business logic through a plain
 * @Service both interfaces' handlers call into — see backend/knowledge/tdt/week3/
 * mode2_toolcall_architecture.md's "Shared Service Extraction" section.
 */
public interface IMode2ToolHandler {

    /**
     * Unique function name matching the Gemini tool declaration built by Mode2ToolDeclarationBuilder.
     */
    String getFunctionName();

    /**
     * Executes tool business logic and returns the response map fed back into the next
     * generateContent call as a functionResponse turn.
     *
     * @param context      formId/workspaceId/userId for this HTTP request — Mode 2's replacement
     *                     for a WebSocketSession attribute bag
     * @param functionCall Jackson JsonNode containing function arguments from Gemini
     * @param callId       Unique tool call ID generated by Gemini
     * @return Response map matching Gemini's functionResponse JSON schema
     */
    Map<String, Object> execute(ChatToolExecutionContext context, JsonNode functionCall, String callId);
}
