package com.reForm.backend.ai.tool.port;

import org.springframework.web.socket.WebSocketSession;
import tools.jackson.databind.JsonNode;

import java.util.Map;

/**
 * STRATEGY INTERFACE: AI FUNCTION CALLING TOOL HANDLER
 * 
 * WHY THIS INTERFACE EXISTS:
 * Eliminates monolithic if-else blocks inside WebSocket adapters. Each tool implementation
 * (e.g. endSession, modifyFormLayout) implements this interface as a Spring @Component.
 * Spring automatically registers all implementations into ToolCallRegistry.
 */
public interface IToolCallHandler {

    /**
     * Unique function name matching Google Gemini tool declaration JSON schema.
     * Example: "endSession", "modifyFormLayout", "searchUserDocument"
     */
    String getFunctionName();

    /**
     * Executes tool business logic and returns response Map to send back to Gemini Live.
     *
     * @param clientSession Active browser WebSocket session
     * @param functionCall  Jackson JsonNode containing function arguments from Gemini
     * @param callId        Unique tool call ID generated by Gemini (required for toolResponse)
     * @return Response map matching Google's toolResponse JSON schema
     */
    Map<String, Object> execute(WebSocketSession clientSession, JsonNode functionCall, String callId);
}
