spring:
  jackson:
    # Changes camelCase Java variables to snake_case in your JSON responses globally
    property-naming-strategy: SNAKE_CASE
    # Prevents dates from being written as ugly computer timestamps (e.g., [2026,6,25])
#    serialization:

  datasource:
    # Changed 5332 to 5432 to match your new docker-compose.yml!
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop #create/update/create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

# =========================================================================
# CUSTOM REFORM PLATFORM CONFIGURATIONS (Root Level)
# =========================================================================
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  security:
      secret: ${JWT_SECRET_KEY}
      expiration-ms: ${EXPIRATION_DURATION:3600000}
